feat(auth): add Default layout component and navigation props
real-festil/doggers pull request #5
Opened 2023-04-13 15:38 UTC by Datmon

2023-04-17 09:21 UTC, real-festil requested changes
почему мы используем интерфейсы а не типы?

2023-04-17 09:21 UTC, real-festil commented on src/app/providers/index.ts
> +const withProviders = compose( withNavigation, withQuery, withUI, withGesture);
what?

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/index.tsx
> +    <Stack.Navigator initialRouteName="Initial" screenOptions={DEFAULT_SCREEN_OPTIONS}>
enum

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/initial/ui.tsx
> +const InitialPage: React.FC<NativeStackScreenProps<AuthNavigationList, AuthNavigationRoutes.Initial>> = ({
FunctionComponent вместо FC

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/initial/ui.tsx
> +const InitialPage: React.FC<NativeStackScreenProps<AuthNavigationList, AuthNavigationRoutes.Initial>> = ({
и импорт из react

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/sign-in/ui.tsx
> +const SignIn: React.FC<NativeStackScreenProps<AuthNavigationList, AuthNavigationRoutes.SignIn>> = ({}) => {
same

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/sign-in/ui.tsx
> +import { AuthNavigationList, AuthNavigationRoutes } from '../types';
тут лучше использовать абсолютный путь для группировки импортов

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/sign-in/ui.tsx
че за пустая строка

2023-04-17 09:21 UTC, real-festil commented on src/pages/auth/sign-up/ui.tsx
> +const SignUp: React.FC<NativeStackScreenProps<AuthNavigationList, AuthNavigationRoutes.SignUp>> = () => {
same

2023-04-17 09:21 UTC, real-festil commented on src/shared/navigator-options/Navigator.options.tsx
> +} as StackNavigationOptions;
дефолтный экспорт и че за название файла

2023-04-17 09:21 UTC, real-festil commented on src/shared/navigator-options/index.tsx
> +export * from './Navigator.options';
и тут экспорт подправить

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/button/Button.tsx
> +import React from 'react';
нейминг файла

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/button/Button.tsx
> +interface IButtonProps extends InterfaceButtonProps {
префикс I кайнда бэд практис

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/button/Button.tsx
> +const Button: React.FC<IButtonProps> = ({ label, children, textProps, ...rest }) => {
FunctionComponent

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/button/index.ts
пустой индекс ман?

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/default-layout/DefaultLayout.tsx
> +interface IDefaultLayoutProps {
префикс

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/default-layout/DefaultLayout.tsx
> +const DefaultLayout: React.FC<IDefaultLayoutProps> = ({
FC

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/default-layout/DefaultLayout.tsx
нейминг файла

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/default-layout/index.ts
> +export default DefaultLayout;
export {default} from './file'

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/scroll-view/ScrollView.tsx
нейминг

2023-04-17 09:21 UTC, real-festil commented on src/shared/ui/scroll-view/index.ts
> +export default ScrollView;
export

2023-04-17 09:21 UTC, real-festil commented on src/widgets/auth/initial-form/ui.tsx
> +
зачем тут пустая строка

2023-04-17 09:21 UTC, real-festil commented on src/widgets/auth/initial-form/ui.tsx
> +const InitialForm: React.FC<InitialFormProps> = ({ navigation }) => {
FC

2023-04-17 09:22 UTC, Datmon commented on src/app/providers/index.ts
> +const withProviders = compose( withNavigation, withQuery, withUI, withGesture);
это принцип.

2023-04-17 09:23 UTC, Datmon commented on src/app/providers/index.ts
> +const withProviders = compose( withNavigation, withQuery, withUI, withGesture);
а вообще я там провайдер на сейф ареа добавлял, а потом выпилил

2023-04-17 09:23 UTC, Datmon commented on src/pages/auth/index.tsx
> +    <Stack.Navigator initialRouteName="Initial" screenOptions={DEFAULT_SCREEN_OPTIONS}>
енюмюмюмюм

2023-04-17 09:24 UTC, Datmon commented on src/pages/auth/initial/ui.tsx
> +const InitialPage: React.FC<NativeStackScreenProps<AuthNavigationList, AuthNavigationRoutes.Initial>> = ({
ну кста у меня все еще там проблемки с импортами, нужно будет еще поковырять тсконфиг

2023-04-17 09:24 UTC, Datmon commented on src/pages/auth/sign-in/ui.tsx
> +import { AuthNavigationList, AuthNavigationRoutes } from '../types';
архитектура так диктует? просто литерали соседняя папка, будет больно...

2023-04-17 09:25 UTC, Datmon commented on src/shared/ui/default-layout/index.ts
> +export default DefaultLayout;
втф
это же не будет дефолтный импорт тогда

2023-04-17 09:26 UTC, Datmon commented on src/shared/ui/scroll-view/ScrollView.tsx
так я спецом так написал, думал так нада
напиши хоть тогда как правильно

2023-04-17 09:26 UTC, Datmon commented on src/shared/ui/scroll-view/index.ts
> +export default ScrollView;
что экспорт?
export {default} from './file'
он опять дефотным не будет

2023-04-17 09:27 UTC, Datmon commented on src/widgets/auth/initial-form/ui.tsx
> +
по-моему это импорт резольвер сделал

2023-04-17 09:27 UTC, Datmon commented on src/widgets/auth/initial-form/ui.tsx
> +const InitialForm: React.FC<InitialFormProps> = ({ navigation }) => {
ок

2023-04-17 09:31 UTC, real-festil commented
https://www.programcreek.com/typescript/?api=react.PropsWithChildren еще такая штука есть

2023-04-17 09:33 UTC, real-festil commented on src/app/providers/index.ts
> +const withProviders = compose( withNavigation, withQuery, withUI, withGesture);
пробел зачем ман

2023-04-17 09:34 UTC, real-festil commented on src/shared/ui/default-layout/index.ts
> +export default DefaultLayout;
будет

2023-04-17 09:34 UTC, real-festil commented on src/shared/ui/scroll-view/ScrollView.tsx
с маленькой буквы и через тире как и везде на проекте

2023-04-17 09:34 UTC, real-festil commented on src/shared/ui/scroll-view/index.ts
> +export default ScrollView;
опять будет

2023-04-23 07:42 UTC, Datmon commented on src/pages/auth/sign-in/ui.tsx
> +import { AuthNavigationList, AuthNavigationRoutes } from '../types';
думаю, правильно так
все абсолютные не относятся напрямую к этому компоненту, а что напрямую зависит от него и находится в папке, и должно быть относительным. Тут наоборот абсолютный путь не ок
+ починил еслинт, шоюы лишние пробелы не делал

2023-04-23 07:44 UTC, Datmon commented on src/shared/ui/default-layout/index.ts
> +export default DefaultLayout;
не работает так, проверил
первый раз такой синтаксис вообще вижу

2023-04-23 07:48 UTC, Datmon commented on src/shared/ui/scroll-view/index.ts
> +export default ScrollView;
не работает
так только обычный импорт делается, дефотный по другому не получается

2023-04-23 10:33 UTC, real-festil commented on src/shared/ui/default-layout/index.ts
> +export default DefaultLayout;
https://github.com/real-festil/casino/blob/master/src/components/Header/index.ts

2023-04-23 10:33 UTC, real-festil commented on src/shared/ui/scroll-view/index.ts
> +export default ScrollView;
https://github.com/real-festil/casino/blob/master/src/components/Header/index.ts

2023-04-26 18:24 UTC, real-festil approved these changes

2023-04-28 08:47 UTC, merged